<?php

define("_Home", "首页");
define("_Hotels", "旅馆");
define("_About", "关于我们");
define("_English", "English");
define("_Malay", "Bahasa Melayu");
define("_Chinese", "中文(简体)");
define("_Where", "目的地");
define("_CameronHighland", "金马仑高原");
define("_KualaLumpur", "吉隆坡");
define("_Kuantan", "关丹");
define("_Malacca", "马六甲");
define("_Penang", "槟城");
define("_Perlis", "玻璃市");
define("_PortDickson", "波德申");
define("_Sarawak", "砂拉越");
define("_Seremban", "芙蓉");
define("_TiomanIsland", "雕门岛");
define("_Checkin", "登记日期");
define("_Checkout", "退房时间");
define("_Guest", "客人的数量");
define("_Submit", "提交");
define("_PopularDestination", "著名的地方");
define("_Reviews", "评语");
define("_RecommendedHotels", "推荐旅馆");
define("_night", "一晚");
define("_OurSatisfiedGuestssays", "我们满意的客人说");
define("_SignUpForALetter", "通讯注册");
define("_SignUpForOurMailingListToGetLatestUpdatesAndOffers", "注册我们的邮件列表以获取最新更新和优惠");
define("_EnterEmail", "你的电子邮件");
define("_Subscribe", "订阅");
define("_SignUpSuccess", "注册成功!");
define("_SignUpFailed", "注册失败!");
define("_SignUpFailedmsg", "请重试!");
define("_LetsGoAgenecy", "Let's Go 机构");
define("_S1", "提供真诚的款待，将在每位客人的心灵上刻出独特的体验;提供真诚的款待，将在每位客人的心灵上刻出独特的体验。");
define("_ContactInformation", "联系信息");
define("_FindHotel", "查找酒店");
define("_First", "第一页");
define("_Last", "最后一页");
define("_FindYourHotel", "查找您的酒店");
define("_JoinUs", "加入我们");
define("_BecomeOurMember", "成为我们的会员");
define("_SignUp", "注册");
define("_YourName", "您的名字");
define("_YourEmail", "您的邮件");
define("_Password", "密码");
define("_RepeatYourPassword", "重复输入你的密码");
define("_PasswordMustMeetTheFollowingRequirements", "密码必须符合以下要求");
define("_AtLeast", "至少");
define("_OneLetter", "一个字母");
define("_OneCapitalLetter", "一个大写字母");
define("_OneNumber", "一个号码");
define("_8Characters", "8 个字");
define("_IAgreeAllStatementsIn", "我同意所有的陈述");
define("_TermsOfService", "服务条款");
define("_Register", "注册");
define("_IAmAlreadyMember", "我已经是会员");
define("_SignIn", "登入");
define("_EnjoyMoreBenefitsNow", "立即享受更多利益");
define("_CreateAnAccount", "创建一个帐户");
define("_RememberMe", "记得我");
define("_LogIn", "登录");
define("_YourProfile", "你的个人资料");
define("_CustomizeYourUserProfile", "自定义您的用户个人资料");
define("_Profile", "个人资料");
define("_Booking", "预订");
define("_YourInfo", "您的信息");
define("_YourBookings", "您的预订");
define("_ViewYourBooking", "查看您的预订");
define("_YourReviews", "您的评论");
define("_CustomizeYourReviews", "自定义您的评论");
define("_Username", "用户名");
define("_Email", "邮件");
define("_EditInfo", "编辑资讯");
define("_LogOut", "登出");
define("_Save", "保存");
define("_Back", "退出");
define("_ForLetsGocom", "对于 Let's Go.com");
define("_Terms", "条款");
define("_History", "历史");
define("_Staff", "员工");
define("_ConnectWithUs", "联系我们");
define("_TermsAndConditionsOfUse", "使用条款及条件");
define("_A1", "通过访问可以从letsgo.com访问的本网站，您同意受这些网站使用条款和条件的约束，并同意您对任何适用的当地法律所规定的协议负责。 如果您不同意这些条款中的任何一项，则禁止您访问此网站。 本网站所含材料受版权和商标法保护。");
define("_UseLicense", "使用许可");
define("_A2", "允许在LetsGo的网站上临时下载一份材料的副本，仅供个人，非商业性的暂时性查看。 这是授予许可，而不是所有权的转让，根据此许可，您不能：");
define("_B1", "修改或复制材料；");
define("_B2", "将这些材料用于任何商业目的或任何公共展示；");
define("_B3", "尝试对LetsGo网站上包含的任何软件进行反向工程;");
define("_B4", "从资料中删除任何版权或其他专有符号； 要么");
define("_B5", "将资料转移给其他人或将资料镜像到其他任何服务器上。");
define("_C1", "这将使LetsGo在违反任何这些限制时终止。 终止后，您的观看权也将终止，无论是印刷形式还是电子形式，您都应销毁拥有的所有下载资料。 这些服务条款是在 ");
define("_C2", "服务条款生成器");
define("_C3", "和");
define("_C4", "隐私政策生成器");
define("_Disclaimer", "免责声明");
define("_A3", "LetsGo网站上的所有资料均按原样提供。 LetsGo不做任何保证，无论是明示还是暗示，因此均不承担所有其他保证。 此外，LetsGo不会就其网站上资料的使用准确性或可靠性或与此类资料或与本网站链接的任何网站有关的任何陈述作出任何陈述。");
define("_Limitations", "局限性");
define("_A4", "即使已通过口头或书面方式告知或通知了LetsGo或本网站的授权代表以下信息，LetsGo或其供应商对因使用或无法使用LetsGo网站上的资料而造成的任何损失不承担责任。 这样的损害。 某些司法管辖区不允许限制默示担保或对意外损坏的责任限制，这些限制可能不适用于您。");
define("_RevisionsAndErrata", "修订和勘误");
define("_A5", "LetsGo网站上显示的材料可能包含技术，印刷或摄影错误。 LetsGo不会保证本网站中的任何材料都是准确，完整或最新的。 LetsGo可以随时更改其网站上包含的资料，恕不另行通知。 LetsGo不承诺更新材料。");
define("_Links", "链接");
define("_A6", "LetsGo尚未审查与其网站链接的所有网站，并对任何此类链接网站的内容概不负责。 任何链接的存在并不意味着LetsGo对该站点的认可。 使用任何链接网站的风险由用户自行承担。");
define("_SiteTermsOfUseModifications", "网站使用条款修改");
define("_A7", "LetsGo可以随时修改其网站使用条款，恕不另行通知。 使用本网站，即表示您同意受这些使用条款和条件的当前版本的约束。");
define("_YourPrivacy", "您的隐私");
define("_A8", "请阅读我们的隐私政策。");
define("_GoverningLaw", "准据法");
define("_A9", "与LetsGo网站有关的任何索赔均受本人法律管辖，无论其法律冲突条款如何。");
define("_ByLetsGocom", "通过 Let's Go.com");
define("_AboutUs", "关于我们");
define("_D1", "远处，在“山”一词的后面，远离Vokalia和Consonantia国家，那里有盲目的文字。 他们分开居住在语义大国语义海的Bookmarksgrove。");
define("_D2", "一条名为Duden的小河在其所在地流淌，并向其提供必要的游憩设施。 这是一个天堂般的国家，在那儿，烤过的句子会飞到您的嘴里。");
define("_D3", "即使是无所不能的“指点器”也无法控制盲文，这几乎是一种非正统的生活。有一天，然而，一小行名为Lorem Ipsum的盲文决定前往遥远的语法世界。");
define("_D4", "Big Oxmox建议她不要这样做，因为那里有成千上万的坏逗号，疯狂的问号和曲折的Semikoli，但Little Blind Text却没有听。 她收拾好七个杂项，将她的首字母缩写带入腰带，让自己走上了道路。");
define("_D5", "当她到达Italic Mountains的第一个山丘时，她对家乡Bookmarksgrove的天际线，Alphabet Village的标题以及她自己的道路Line Line的副线有了最后的了解。 可怜的一个反复问了她的脸颊，然后她继续前进。");
define("_D6", "当她到达Italic Mountains的第一个山丘时，她对家乡Bookmarksgrove的天际线，Alphabet Village的标题以及她自己的道路Line Line的副线有了最后的了解。 可怜的一个反复问了她的脸颊，然后她继续前进。");
define("_D7", "在途中，她遇到了副本。 该副本警告“小盲文”，它的来源将被重写一千遍，而从其原处遗留下的一切都将是单词，“小盲文”应转身回到自己的安全国家。");
define("_D8", "但是复制品说的话并没有说服她，因此不久之后，一些阴险的复制作家伏击了她，让她与Longe和Parole一起喝醉，然后将她拖入他们的经纪公司，在那里他们虐待了她。");
define("_OurStaffs", "我们的员工");
define("_MeetOurLovelyMembers", "认识我们可爱的成员");
define("_FrontEndDeveloper", "前端开发人员");
define("_ReportWriter", "报告撰写人");
define("_BackEndDeveloper", "后端开发人员");
define("_HotelOverview", "酒店概况");
define("_BookNow", "现在预订");
define("_Reservation", "预留");
define("_ReserveAtLetsGocom", "预留在 Let's Go.com");
define("_ReservingAs", "预留为");
define("_ReservationInformation", "预留信息");
define("_TypeOfRoom", "房间类型");
define("_BeddingType", "寝具类型");
define("_NoOfRooms", "房间数量");
define("_MealPlan", "进食计划");
define("_Remarks", "备注");
define("_HUMANVERIFICATION", "真人验证");
define("_EnterThisCode", "输入此代码");
define("_Code", "代码");
define("_BookingSuccessful", "预订成功!");
define("_BookingSuccessfulmsg", "感谢您向我们预订!");
define("_BookingFailed", "预订失败!");
define("_BookingFailedmsg", "请再试一次!");
define("_PersonalInformation", "个人信息");
define("_Title", "标题");
define("_FirstName", "名字");
define("_LastName", "姓");
define("_PassportCountry", "护照国家");
define("_PhoneNumber", "电话号码");
define("_AlreadyAMember", "已经是会员?");
define("_SignInHere", "在这里登入!");
define("_ChosenHotel", "选择的旅馆");
define("_ReviewSuccessful", "评论已发布!");
define("_ReviewSuccessfulmsg", "感谢您的评论!");
define("_ReviewFailed", "评论发布失败!");
define("_ReviewFailedmsg", "请再试一次!");
define("_ReviewingAs", "评论为");
define("_RatingAnd", "评分 和");
define("_CustomerReviews", "客户评论");
define("_WriteYourReview", "提交您的评论");
define("_SignInReview", "登录发表评论");
define("_MyNewRoutine", "我的新程序：旅程。 探索。 发现。 重复。");
define("_WhenExploring", "当我探索世界时，就是我感到宾至如归的时候");
define("_WeLoveToTell", "我们喜欢告诉我们成功的地方是远在山字后面，远离Vokalia和Consonantia国家的地方，那里有盲目的文字。");
define("_TakeMemories", "索起回忆");
define("_LeaveFootPrints", "留下足迹");
define("_AlwaysSay", "总是说");
define("_YestoNewAdv", "是的! 新冒险!");
define("_ExploreOurTA", "探索我们最好的旅行社");
define("_ExperienceThe", "体验");
define("_BestTripEver", "有史以来最好的旅行");
define("_Edit", "编辑");
define("_Delete", "删除");
define("_NoData", "没有数据");
define("_ReviewTitle", "评语标题");
define("_Rate", "评分");
define("_RatingDate", "评级日期");
define("_Action", "行动");
define("_BookingID", "预订编号");
define("_BookingDate", "预订日期");


?>