<?php

define("_Home", "Laman Utama");
define("_Hotels", "Hotels");
define("_About", "Tentang");
define("_English", "English");
define("_Malay", "Bahasa Melayu");
define("_Chinese", "中文(简体)");
define("_Where", "Destinasi");
define("_CameronHighland", "Cameron Highland");
define("_KualaLumpur", "Kuala Lumpur");
define("_Kuantan", "Kuantan");
define("_Malacca", "Melaka");
define("_Penang", "Penang");
define("_Perlis", "Perlis");
define("_PortDickson", "Port Dickson");
define("_Sarawak", "Sarawak");
define("_Seremban", "Seremban");
define("_TiomanIsland", "PulauTioman");
define("_Checkin", "Tarikh Daftar");
define("_Checkout", "Tarikh Keluar");
define("_Guest", "Tetamu");
define("_Submit", "Hantar");
define("_PopularDestination", "Popular Destinasi");
define("_Reviews", "Komen");
define("_RecommendedHotels", "Hotel yang Disyorkan");
define("_night", "malam");
define("_OurSatisfiedGuestssays", "Kata daripada tetamu yang berpuas hati");
define("_SignUpForALetter", "Tanda Daftar Buletin");
define("_SignUpForOurMailingListToGetLatestUpdatesAndOffers", "Daftar untuk daftar mel kami untuk mendapatkan kemas kini dan tawaran terkini");
define("_EnterEmail", "Email anda");
define("_Subscribe", "Langgan");
define("_SignUpSuccess", "Pendaftaran Berjaya!");
define("_SignUpFailed", "Pendaftaran Tidak Berjaya!");
define("_SignUpFailedmsg", "Sila cuba lagi!");
define("_LetsGoAgenecy", "Let's Go Agensi");
define("_S1", "Untuk memberikan keramahan tulus yang tulus, itu akan mengukir pengalaman unik di hati dan fikiran setiap tetamu. Untuk memberikan keramahan tulus, yang akan mengukir pengalaman unik di hati dan fikiran setiap tetamu.");
define("_ContactInformation", "Maklumat perhubungan");
define("_FindHotel", "Cari Hotel");
define("_First", "Utama");
define("_Last", "Terakhir");
define("_FindYourHotel", "Cari Hotel Anda");
define("_JoinUs", "Sertai kami");
define("_BecomeOurMember", "Menjadi Ahli Kami");
define("_SignUp", "Daftar");
define("_YourName", "Nama Anda");
define("_YourEmail", "Emel Anda");
define("_Password", "Kata Laluan");
define("_RepeatYourPassword", "Ulangi Kata Lalaun Anda");
define("_PasswordMustMeetTheFollowingRequirements", "Kata Laluan perlu memenuhi keperluan berikut");
define("_AtLeast", "Sekurang-kurangnya");
define("_OneLetter", "Satu Huruf");
define("_OneCapitalLetter", "Satu Huruf Besar");
define("_OneNumber", "Satu Nombor");
define("_8Characters", "Lapan watak");
define("_IAgreeAllStatementsIn", "Saya setuju semua pernyataan di");
define("_TermsOfService", "Syarat Perkhidmatan");
define("_Register", "Daftar");
define("_IAmAlreadyMember", "Saya sudah menjadi ahli");
define("_SignIn", "Log Masuk");
define("_EnjoyMoreBenefitsNow", "Nikmati lebih banyak manfaat sekarang");
define("_CreateAnAccount", "Buat satu akaun");
define("_RememberMe", "Ingat saya");
define("_LogIn", "Log Masuk");
define("_YourProfile", "Profil Anda");
define("_CustomizeYourUserProfile", "Sesuaikan Profil Pengguna Anda");
define("_Profile", "Profil");
define("_Booking", "Tempahan");
define("_YourInfo", "Maklumat Anda");
define("_YourBookings", "Tempahan Anda");
define("_ViewYourBooking", "Lihat Tempahan Anda");
define("_YourReviews", "Komen Anda");
define("_CustomizeYourReviews", "Sesuaikan Komen Anda");
define("_Username", "Nama pengunna");
define("_Email", "E-mel");
define("_EditInfo", "Edit Maklumat");
define("_LogOut", "Log Keluar");
define("_Save", "Simpan");
define("_Back", "Balik");
define("_ForLetsGocom", "Bagi Let's Go.com");
define("_Terms", "Syarat");
define("_History", "Sejarah");
define("_Staff", "Kakitangan");
define("_ConnectWithUs", "Sambung Bersama");
define("_TermsAndConditionsOfUse", "Terma dan Syarat Penggunaan");
define("_A1", "Dengan mengakses Laman web ini, dapat diakses dari letsgo.com, Anda setuju untuk terikat dengan Syarat dan Ketentuan Penggunaan Laman Web ini dan bersetuju bahawa anda bertanggung jawab atas perjanjian dengan undang-undang tempatan yang berlaku. Sekiranya anda tidak bersetuju dengan mana-mana syarat ini, anda dilarang mengakses laman web ini. Bahan-bahan yang terdapat di dalam Situs Web ini dilindungi oleh undang-undang hak cipta dan merek dagang.");
define("_UseLicense", "Gunakan Lesen");
define("_A2", "Kebenaran diberikan untuk memuat turun sementara satu salinan bahan di Laman Web LetsGo untuk tontonan sementara dan bukan komersial sahaja. Ini adalah pemberian lesen, bukan pemindahan hakmilik, dan di bawah lesen ini anda tidak boleh:");
define("_B1", "mengubah suai atau menyalin bahan;");
define("_B2", "gunakan bahan untuk tujuan komersial atau untuk pameran awam;");
define("_B3", "berusaha untuk membuat kejuruteraan semula perisian yang terdapat di Laman Web LetsGo;");
define("_B4", "hapus nota hak cipta atau hak milik lain dari bahan; atau");
define("_B5", "memindahkan bahan tersebut kepada orang lain atau mencerminkan bahan tersebut di mana-mana pelayan lain.");
define("_C1", "Ini akan memungkinkan LetsGo untuk menghentikan pelanggaran sekatan ini. Setelah penamatan, hak tontonan anda juga akan dihentikan dan anda harus memusnahkan sebarang bahan yang dimuat turun dalam simpanan anda sama ada yang dicetak atau format elektronik. Syarat Perkhidmatan ini telah dibuat dengan bantuan ");
define("_C2", "Penjana Syarat Perkhidmatan");
define("_C3", "dan juga");
define("_C4", "Penjana Dasar Privasi");
define("_Disclaimer", "Penafian");
define("_A3", "Semua bahan di Laman web LetsGo disediakan sebagaimana adanya. LetsGo tidak memberikan jaminan, boleh dinyatakan atau tersirat, oleh itu membatalkan semua jaminan lain. Selanjutnya, LetsGo tidak membuat pernyataan mengenai ketepatan atau kebolehpercayaan penggunaan bahan di Laman Webnya atau yang berkaitan dengan bahan tersebut atau laman web yang dihubungkan dengan Laman Web ini.");
define("_Limitations", "Batasan");
define("_A4", "LetsGo atau pembekalnya tidak akan bertanggungjawab atas sebarang kerosakan yang timbul dengan penggunaan atau ketidakmampuan untuk menggunakan bahan-bahan di Laman Web LetsGo, walaupun LetsGo atau wakil yang sah dari Laman web ini telah diberitahu, secara lisan atau bertulis, mengenai kemungkinan kerosakan tersebut. Sebilangan bidang kuasa tidak membenarkan pembatasan jaminan tersirat atau had tanggungjawab untuk kerosakan sampingan, batasan ini mungkin tidak berlaku untuk anda.");
define("_RevisionsAndErrata", "Semakan Dan Errata");
define("_A5", "Bahan yang muncul di Laman web LetsGo mungkin merangkumi kesalahan teknikal, tipografi, atau fotografi. LetsGo tidak akan menjanjikan bahawa mana-mana bahan dalam Laman Web ini tepat, lengkap, atau terkini. LetsGo boleh mengubah bahan yang terdapat di Laman Webnya pada bila-bila masa tanpa pemberitahuan. LetsGo tidak membuat komitmen untuk mengemas kini bahan.");
define("_Links", "Pautan");
define("_A6", "LetsGo belum mengkaji semua laman web yang dipautkan ke Laman Webnya dan tidak bertanggungjawab terhadap kandungan laman web tersebut. Kehadiran pautan tidak bermaksud sokongan oleh LetsGo dari laman web ini. Penggunaan laman web yang dipautkan adalah risiko pengguna sendiri.");
define("_SiteTermsOfUseModifications", "Pengubahsuaian Syarat Penggunaan Tapak");
define("_A7", "LetsGo dapat merevisi Syarat Penggunaan ini untuk Laman Webnya pada bila-bila masa tanpa pemberitahuan terlebih dahulu. Dengan menggunakan Laman web ini, anda setuju untuk terikat dengan versi Terma dan Syarat Penggunaan ini.");
define("_YourPrivacy", "Privasi anda");
define("_A8", "Sila baca Dasar Privasi kami.");
define("_GoverningLaw", "Undang-undang Pemerintahan");
define("_A9", "Segala tuntutan yang berkaitan dengan Laman web LetsGo akan diatur oleh undang-undang saya tanpa memperhatikan pertentangan undang-undangnya.");
define("_ByLetsGocom", "Oleh Let's Go.com");
define("_AboutUs", "Tentang Kita");
define("_D1", "Jauh di belakang kata gunung, jauh dari negara Vokalia dan Consonantia, terdapat teks-teks buta. Terpisah mereka tinggal di Bookmarksgrove tepat di pesisir Semantik, lautan bahasa yang besar.");
define("_D2", "Sebuah sungai kecil bernama Duden mengalir di tempat mereka dan membekalkannya dengan wilayah yang diperlukan. Ini adalah negara paradisematis, di mana bahagian-bahagian kalimat panggang terbang ke mulut anda.");
define("_D3", "Bahkan Penunjuk yang sangat berkuasa tidak mempunyai kawalan tentang teks buta, ia adalah kehidupan yang hampir tidak ortografik. Suatu hari namun sebilangan kecil teks buta dengan nama Lorem Ipsum memutuskan untuk pergi ke Dunia Tatabahasa yang jauh.");
define("_D4", "The Big Oxmox menasihatinya untuk tidak melakukannya, kerana terdapat ribuan koma buruk, Tanda tanya liar dan Semikoli yang licik, tetapi Teks Buta Kecil tidak mendengar. Dia mengemas tujuh versinya, memasukkannya ke tali pinggang dan membuat dirinya dalam perjalanan.");
define("_D5", "Ketika dia sampai di bukit pertama Pergunungan Itali, dia melihat pemandangan terakhir di kaki langit kampung halamannya Bookmarksgrove, tajuk Alphabet Village dan garis bawah jalannya sendiri, Line Lane. Sayang sekali sebuah pertanyaan retorik mengalir di pipinya, lalu dia meneruskan perjalanannya.");
define("_D6", "Ketika dia sampai di bukit pertama Pergunungan Itali, dia melihat pemandangan terakhir di kaki langit kampung halamannya Bookmarksgrove, tajuk Alphabet Village dan garis bawah jalannya sendiri, Line Lane. Sayang sekali sebuah pertanyaan retorik mengalir di pipinya, lalu dia meneruskan perjalanannya.");
define("_D7", "Dalam perjalanannya dia menemui satu salinan. Salinan itu memperingatkan Little Blind Text, bahawa dari mana asalnya akan ditulis semula seribu kali dan segala yang tersisa dari asalnya adalah perkataan dan Little Blind Text harus berbalik dan kembali ke tulisannya sendiri, negara yang selamat.");
define("_D8", "Tetapi apa-apa salinan yang dikatakan tidak dapat meyakinkannya dan tidak perlu lama sehingga beberapa Penulis Salin yang menipu menyergapnya, membuatnya mabuk dengan Longe dan Parole dan menyeretnya ke agensi mereka, di mana mereka menyalahgunakannya untuk mereka.");
define("_OurStaffs", "Kakitangan Kami ");
define("_MeetOurLovelyMembers", "Temui ahli-ahli kami yang hebat");
define("_FrontEndDeveloper", "Pembangun Front-End");
define("_ReportWriter", "Laporan Penulis");
define("_BackEndDeveloper", "Pembangun Back-End");
define("_HotelOverview", "Gambaran Keseluruhan Hotel");
define("_BookNow", "Tempah Sekarang");
define("_Reservation", "Tempahan");
define("_ReserveAtLetsGocom", "Tempahan di Let's Go.com");
define("_ReservingAs", "Tempahan sebagai");
define("_ReservationInformation", "Tempahan Maklumat");
define("_TypeOfRoom", "Jenis Bilik");
define("_BeddingType", "Jenis Tempat Tidur");
define("_NoOfRooms", "Jumlah Bilik");
define("_MealPlan", "Pelan Makanan");
define("_Remarks", "Kenyataan");
define("_HUMANVERIFICATION", "PENGESAHAN MANUSIA");
define("_EnterThisCode", "Masukkan kod ini");
define("_Code", "Kod");
define("_BookingSuccessful", "Tempahan Berjaya!");
define("_BookingSuccessfulmsg", "Terima kasih membuat tempahan dengan kita!");
define("_BookingFailed", "Tempahan Tidak Berjaya!");
define("_BookingFailedmsg", "Sila cuba lagi!");
define("_PersonalInformation", "Maklumat peribadi");
define("_Title", "Tajuk");
define("_FirstName", "Nama Pertama");
define("_LastName", "Nama Akhir");
define("_PassportCountry", "Negara Pasport");
define("_PhoneNumber", "Nombor telefon");
define("_AlreadyAMember", "Sudah menjadi ahli?");
define("_SignInHere", "Log masuk di sini!");
define("_ChosenHotel", "Hotel Pilihan");
define("_ReviewSuccessful", "Review Submitted!");
define("_ReviewSuccessfulmsg", "Thank you for submitting your review!");
define("_ReviewFailed", "Review Not Submitted!");
define("_ReviewFailedmsg", "Please try again!");
define("_ReviewingAs", "Mengkaji sebagai");
define("_RatingAnd", "Penilaian &");
define("_CustomerReviews", "Komen Pelanggan");
define("_WriteYourReview", "Write Your Reviews");
define("_SignInReview", "Log masuk untuk komen");
define("_MyNewRoutine", "Rutin baru saya: Perjalanan. Meneroka. Cari. Ulangi.");
define("_WhenExploring", "Ketika saya menjelajah dunia adalah ketika saya merasa paling selesa di rumah");
define("_WeLoveToTell", "Kami suka memberitahu kejayaan kami yang jauh, di belakang kata gunung, jauh dari negara Vokalia dan Consonantia, di sana terdapat teks-teks yang buta.");
define("_TakeMemories", "Ambil Kenangan");
define("_LeaveFootPrints", "Tinggalkan jejak kaki");
define("_AlwaysSay", "Selalu berkata");
define("_YestoNewAdv", "YES untuk pengembaraan baru");
define("_ExploreOurTA", "Terokai agensi pelancongan terbaik kami");
define("_ExperienceThe", "Alami");
define("_BestTripEver", "Perjalanan Terbaik yang Pernah Ada");
define("_Edit", "Tukar");
define("_Delete", "Padam");
define("_NoData", "Tiada Data");
define("_ReviewTitle", "Tajuk Kajian");
define("_Rate", "Penilaian");
define("_RatingDate", "Tarikh penilaian");
define("_Action", "Tindakan");
define("_BookingID", "Tempahan ID");
define("_BookingDate", "Tarikh Tempahan");


?>