<?php

define("_Home", "Home");
define("_Hotels", "Hotels");
define("_About", "About");
define("_English", "English");
define("_Malay", "Bahasa Melayu");
define("_Chinese", "中文(简体)");
define("_Where", "Where");
define("_CameronHighland", "Cameron Highland");
define("_KualaLumpur", "Kuala Lumpur");
define("_Kuantan", "Kuantan");
define("_Malacca", "Malacca");
define("_Penang", "Penang");
define("_Perlis", "Perlis");
define("_PortDickson", "Port Dickson");
define("_Sarawak", "Sarawak");
define("_Seremban", "Seremban");
define("_TiomanIsland", "Tioman Island");
define("_Checkin", "Check-in");
define("_Checkout", "Check-out");
define("_Guest", "Guest");
define("_Submit", "Submit");
define("_PopularDestination", "Popular Destination");
define("_Reviews", "Reviews");
define("_RecommendedHotels", "Recommended Hotels");
define("_night", "night");
define("_OurSatisfiedGuestssays", "Our Satisfied Guests says");
define("_SignUpForALetter", "Sign Up For A Letter");
define("_SignUpForOurMailingListToGetLatestUpdatesAndOffers", "Sign Up For Our Mailing List To Get Latest Updates And Offers");
define("_EnterEmail", "Enter your email");
define("_Subscribe", "Subscribe");
define("_SignUpSuccess", "Sign Up Successfully!");
define("_SignUpFailed", "Sign Up Failed!");
define("_SignUpFailedmsg", "Please try again!");
define("_LetsGoAgenecy", "Let's Go Agency");
define("_S1", "To provide genuine heartfelt hospitality, that will engrave a unique experience in the heart and mind of every guest.To provide genuine heartfelt hospitality, that will engrave a unique experience in the heart and mind of every guest.");
define("_ContactInformation", "Contact Information");
define("_FindHotel", "Find Hotel");
define("_First", "First");
define("_Last", "Last");
define("_FindYourHotel", "Find Your Hotel");
define("_JoinUs", "Join Us");
define("_BecomeOurMember", "Become Our Member");
define("_SignUp", "Sign Up");
define("_YourName", "Your Name");
define("_YourEmail", "Your Email");
define("_Password", "Password");
define("_RepeatYourPassword", "Repeat your password");
define("_PasswordMustMeetTheFollowingRequirements", "Password must meet the following requirements");
define("_AtLeast", "At Least");
define("_OneLetter", "One Letter");
define("_OneCapitalLetter", "One Capital Letter");
define("_OneNumber", "One Number");
define("_8Characters", "8 Characters");
define("_IAgreeAllStatementsIn", "I agree all statements in");
define("_TermsOfService", "Terms Of Service");
define("_Register", "Register");
define("_IAmAlreadyMember", "I am already member");
define("_SignIn", "Sign In");
define("_EnjoyMoreBenefitsNow", "Enjoy More Benefit Now");
define("_CreateAnAccount", "Create an account");
define("_RememberMe", "Remember Me");
define("_LogIn", "Log in");
define("_YourProfile", "Your Profile");
define("_CustomizeYourUserProfile", "Customize Your User Profile");
define("_Profile", "Profile");
define("_Booking", "Booking");
define("_YourInfo", "Your Info");
define("_YourBookings", "Your Bookings");
define("_YourReviews", "Your Reviews");
define("_Username", "Username");
define("_Email", "Email");
define("_EditInfo", "Edit Info");
define("_LogOut", "Log out");
define("_Save", "Save");
define("_Back", "Back");
define("_ForLetsGocom", "For Let's Go.com");
define("_Terms", "Terms");
define("_History", "History");
define("_Staff", "Staff");
define("_ConnectWithUs", "Connect With Us");
define("_TermsAndConditionsOfUse", "Terms And Conditions Of Use");
define("_A1", "By accessing this Website, accessible from letsgo.com, you are agreeing to be bound by these Website Terms and Conditions of Use and agree that you are responsible for the agreement with any applicable local laws. If you disagree with any of these terms, you are prohibited from accessing this site. The materials contained in this Website are protected by copyright and trade mark law.");
define("_UseLicense", "Use License");
define("_A2", "Permission is granted to temporarily download one copy of the materials on LetsGo's Website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:");
define("_B1", "modify or copy the materials;");
define("_B2", "use the materials for any commercial purpose or for any public display;");
define("_B3", "attempt to reverse engineer any software contained on LetsGo's Website;");
define("_B4", "remove any copyright or other proprietary notations from the materials; or");
define("_B5", "transferring the materials to another person or mirror the materials on any other server.");
define("_C1", "This will let LetsGo to terminate upon violations of any of these restrictions. Upon termination, your viewing right will also be terminated and you should destroy any downloaded materials in your possession whether it is printed or electronic format. These Terms of Service has been created with the help of the ");
define("_C2", "Terms Of Service Generator");
define("_C3", "and the");
define("_C4", "Privacy Policy Generator");
define("_Disclaimer", "Disclaimer");
define("_A3", "All the materials on LetsGo’s Website are provided as is. LetsGo makes no warranties, may it be expressed or implied, therefore negates all other warranties. Furthermore, LetsGo does not make any representations concerning the accuracy or reliability of the use of the materials on its Website or otherwise relating to such materials or any sites linked to this Website.");
define("_Limitations", "Limitations");
define("_A4", "LetsGo or its suppliers will not be hold accountable for any damages that will arise with the use or inability to use the materials on LetsGo’s Website, even if LetsGo or an authorize representative of this Website has been notified, orally or written, of the possibility of such damage. Some jurisdiction does not allow limitations on implied warranties or limitations of liability for incidental damages, these limitations may not apply to you.");
define("_RevisionsAndErrata", "Revisions And Errata");
define("_A5", "The materials appearing on LetsGo’s Website may include technical, typographical, or photographic errors. LetsGo will not promise that any of the materials in this Website are accurate, complete, or current. LetsGo may change the materials contained on its Website at any time without notice. LetsGo does not make any commitment to update the materials.");
define("_Links", "Links");
define("_A6", "LetsGo has not reviewed all of the sites linked to its Website and is not responsible for the contents of any such linked site. The presence of any link does not imply endorsement by LetsGo of the site. The use of any linked website is at the user’s own risk.");
define("_SiteTermsOfUseModifications", "Site Terms Of Use Modifications");
define("_A7", "LetsGo may revise these Terms of Use for its Website at any time without prior notice. By using this Website, you are agreeing to be bound by the current version of these Terms and Conditions of Use.");
define("_YourPrivacy", "Your Privacy");
define("_A8", "Please read our Privacy Policy.");
define("_GoverningLaw", "Governing Law");
define("_A9", "Any claim related to LetsGo's Website shall be governed by the laws of my without regards to its conflict of law provisions.");
define("_ByLetsGocom", "By Let's Go.com");
define("_AboutUs", "About Us");
define("_D1", "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.");
define("_D2", "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.");
define("_D3", "Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.");
define("_D4", "The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way.");
define("_D5", "When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.");
define("_D6", "When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.");
define("_D7", "On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word and the Little Blind Text should turn around and return to its own, safe country.");
define("_D8", "But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.");
define("_OurStaffs", "Our Staffs");
define("_MeetOurLovelyMembers", "Meet Our Lovely Members");
define("_FrontEndDeveloper", "Front-End Developer");
define("_ReportWriter", "Report Writer");
define("_BackEndDeveloper", "Back-End Developer");
define("_HotelOverview", "Hotel Overview");
define("_BookNow", "Book Now");
define("_Reservation", "Reservation");
define("_ReserveAtLetsGocom", "Reserve At Let's Go.com");
define("_ReservingAs", "Reserving as");
define("_ReservationInformation", "Reservation Information");
define("_TypeOfRoom", "Type Of Room");
define("_BeddingType", "Bedding Type");
define("_NoOfRooms", "No Of Room");
define("_MealPlan", "Meal Plan");
define("_Remarks", "Remarks");
define("_HUMANVERIFICATION", "HUMAN VERIFICATION");
define("_EnterThisCode", "Enter this code below");
define("_Code", "Code");
define("_BookingSuccessful", "Booking Successful!");
define("_BookingSuccessfulmsg", "Thank you for booking with us!");
define("_BookingFailed", "Booking Failed!");
define("_BookingFailedmsg", "Please try again!");
define("_PersonalInformation", "Personal Information");
define("_Title", "Title");
define("_FirstName", "First Name");
define("_LastName", "Last Name");
define("_PassportCountry", "Passport Country");
define("_PhoneNumber", "Phone Number");
define("_AlreadyAMember", "Already a member?");
define("_SignInHere", "Sign in here!");
define("_ChosenHotel", "Chosen Hotel");
define("_ReviewSuccessful", "Review Submitted!");
define("_ReviewSuccessfulmsg", "Thank you for submitting your review!");
define("_ReviewFailed", "Review Not Submitted!");
define("_ReviewFailedmsg", "Please try again!");
define("_ReviewingAs", "Reviewing as");
define("_RatingAnd", "Ratings &");
define("_CustomerReviews", "Customer Reviews");
define("_WriteYourReview", "Write Your Reviews");
define("_SignInReview", "Sign in to review");
define("_MyNewRoutine", "My new routine: Journey. Explore. Discover. Repeat.");
define("_WhenExploring", "When I'm exploring the world is when I feel most at home");
define("_WeLoveToTell", "We love to tell our successful far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.");
define("_TakeMemories", "Take Memories");
define("_LeaveFootPrints", "Leave Footprints");
define("_AlwaysSay", "Always say");
define("_YestoNewAdv", "YES to new adventure");
define("_ExploreOurTA", "Explore our most travel agency");
define("_ExperienceThe", "Experience the");
define("_BestTripEver", "Best Trip Ever");

?>